services:
  - type: web
    name: ai-assistant-pro-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ALLOWED_ORIGINS
        value: https://ai-assistant-c7ktnvjxz-robertotos-projects.vercel.app,https://ai-assistant-13sh6yauv-robertotos-projects.vercel.app
